In [1]:
import pandas as pd
import seaborn as sb
import sklearn.neural_network as sknn

In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mpl

In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
##################################################################

In [5]:
###############################################
# load titanic dataset from seaborn
# drop embark_down and deck
# impute missing values in 'age' by mean of ages in each class
# hint: use groupby in step 1 and iterrows in step 2

In [6]:
df=sb.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [7]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df.drop(['embark_town','deck'], axis=1, inplace=True)

In [9]:
df.groupby('pclass')['age'].mean()

pclass
1    38.233441
2    29.877630
3    25.140620
Name: age, dtype: float64

In [10]:
ls = [0] + list(df.groupby('pclass')['age'].mean())
ls

[0, 38.233440860215055, 29.87763005780347, 25.14061971830986]

In [11]:
for index,row in df.iterrows():
    if np.isnan(row.age):
        df.loc[index, 'age'] = ls[row.pclass]
df.isna().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      2
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

In [12]:
df = df.dropna()

In [13]:
df.isna().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      0
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

In [14]:
#############################
# dummy value all the cat features
# benchmark time of a block of fit/predict/confusion matrix (%%time)
# RF - changing number of estimators to reach 100% accuracy
# MLP - changing number of interatios to reach 100% accuracy

In [15]:
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male alive  alone  
0    man        True    no  False  
1  woman       False   yes  False  
2  woman       False   yes   True

In [16]:
df = pd.get_dummies(df, columns=['sex','embarked','class','who','adult_male','alone'])
df.head()

survived  pclass   age  sibsp  parch     fare alive  sex_female  sex_male  \
0         0       3  22.0      1      0   7.2500    no           0         1   
1         1       1  38.0      1      0  71.2833   yes           1         0   
2         1       3  26.0      0      0   7.9250   yes           1         0   
3         1       1  35.0      1      0  53.1000   yes           1         0   
4         0       3  35.0      0      0   8.0500    no           0         1   

   embarked_C  ...  class_First  class_Second  class_Third  who_child  \
0           0  ...            0             0            1          0   
1           1  ...            1             0            0          0   
2           0  ...            0             0            1          0   
3           0  ...            1             0            0          0   
4           0  ...            0             0            1          0   

   who_man  who_woman  adult_male_False  adult_male_True  alone_False  \
0        1          0                 0                1            1   
1        0          1                 1                0            1   
2        0          1                 1                0            0   
3        0          1                 1                0            1   
4        1          0                 0                1            0   

   alone_True  
0           0  
1           0  
2           1  
3           0  
4           1  

[5 rows x 22 columns]

In [17]:
df.drop(['alive'], axis=1, inplace=True)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 21 columns):
survived            889 non-null int64
pclass              889 non-null int64
age                 889 non-null float64
sibsp               889 non-null int64
parch               889 non-null int64
fare                889 non-null float64
sex_female          889 non-null uint8
sex_male            889 non-null uint8
embarked_C          889 non-null uint8
embarked_Q          889 non-null uint8
embarked_S          889 non-null uint8
class_First         889 non-null uint8
class_Second        889 non-null uint8
class_Third         889 non-null uint8
who_child           889 non-null uint8
who_man             889 non-null uint8
who_woman           889 non-null uint8
adult_male_False    889 non-null uint8
adult_male_True     889 non-null uint8
alone_False         889 non-null uint8
alone_True          889 non-null uint8
dtypes: float64(2), int64(4), uint8(15)
memory usage: 61.6 KB


In [19]:
X = df.loc[:, df.columns != 'survived']
y = df.loc[:, df.columns == 'survived']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
%%time
model = sknn.MLPClassifier(max_iter=50)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[159  25]
 [ 28  82]]
              precision    recall  f1-score   support

           0       0.85      0.86      0.86       184
           1       0.77      0.75      0.76       110

    accuracy                           0.82       294
   macro avg       0.81      0.80      0.81       294
weighted avg       0.82      0.82      0.82       294

Wall time: 134 ms


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=47)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[147  37]
 [ 32  78]]
              precision    recall  f1-score   support

           0       0.82      0.80      0.81       184
           1       0.68      0.71      0.69       110

    accuracy                           0.77       294
   macro avg       0.75      0.75      0.75       294
weighted avg       0.77      0.77      0.77       294



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
%%time
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(max_iter=400, batch_size=30, random_state=47)
mlp.fit(X_train, y_train)
y_pred1 = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


[[159  25]
 [ 28  82]]
              precision    recall  f1-score   support

           0       0.85      0.86      0.86       184
           1       0.77      0.75      0.76       110

    accuracy                           0.82       294
   macro avg       0.81      0.80      0.81       294
weighted avg       0.82      0.82      0.82       294

Wall time: 379 ms


In [24]:
df.shape

(889, 21)

In [25]:
X_train.shape

(595, 20)